### ISSUE TITLE
Would you like to tell about purpose of this port ?

### ISSUE THREAD

**Issue by nvcken** [KhaJS/Kha#1]
While can compile to JS with Kha,

**Comment by troyedwardsjr** [comment]
You can write HTML5 Kha applications directly from Javascript / Typescript without having to use the Haxe language.

Haxe is a nice language but it lacks many specific features that Typescript has and vice versa. You can also arbitrarily import any Javascript library without having to write Haxe externs, and there are many more Typescript definitions available for JS libraries than there are Haxe externs. 

The port is currently fully usable, but still needs to be improved. I'll create an example and post about it more publicly when I get around to it.

**Comment by nvcken** [comment]
Ideally, I saw https://github.com/openfl/openfl-samples-ts, have you considered likes this approach mix TS & Kha , instead port entirely Kha > TS

**Comment by troyedwardsjr** [comment]
OpenFL is doing the same thing I'm doing. We're both using generators via `hxgenjs` to create the port. The only difference is I'm writing scripts to generate a useful output while Joshua Granick from OpenFL had to write many of the Typescript definitions by hand based on hxgenjs's default output.

**Comment by nvcken** [comment]
Thanks for your explanation.
